# Faire make ... pour exectuer les commandes associées
# typiquement: make all + make traitement execute le programme puis génère les frames
# enchainer avec make movie crée l'animation
#
all :
	gfortran test.f90 -o test
	./test

program :
	gfortran test.f90 -o test 

